{{- if .Values.onePassword.createItem }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.onePassword.existingSecretName }}
  labels:
    app.kubernetes.io/name: {{ include "grafana2.name" . }}
    helm.sh/chart: {{ include "grafana2.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    operator.1password.io/auto-restart: {{ ternary "true" "false" .Values.onePassword.autoRestart | quote }}
spec:
  itemPath: "vaults/{{ required "onePassword.vault is required when onePassword.createItem=true" .Values.onePassword.vault }}/items/{{ .Values.onePassword.itemName }}"
{{- end }}
